version: '3'
services:
  php:
    build: .
    volumes:
        - ./web:/var/www/app
    environment:
        TZ: Asia/Bangkok
    ports:
        - 8000:8000
    command: "php -S 0.0.0.0:8000 -t public"